const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { validate, saveConfig, loadConfig, startSetup } = require('./setup');
const input = () => ({ credentials: { type: 'service_account', project_id: 'demo', client_email: 'bot@demo.iam.gserviceaccount.com', private_key: 'test-only' }, databaseURL: 'https://demo-default-rtdb.europe-west1.firebasedatabase.app', apiKey: 'testkey1234', username: 'admin', password: 'test-password-123', clan: 'ODIN', interval: 120 });
test('setup rejects unsafe URLs and weak credentials', () => {
  for (const patch of [{ databaseURL: 'http://127.0.0.1' }, { databaseURL: 'https://evil.test' }, { databaseURL: 'https://demo.firebaseio.com/secret' }, { password: 'short' }, { origin: 'https://demo.test/path' }, { clan: '../bad' }, { webhook: 'https://discord.com/api/webhooks/1/a/../../x' }]) assert.throws(() => validate({ ...input(), ...patch }));
  assert.equal(validate(input()).interval, 120);
});
test('configuration is hashed, reloadable and never overwritten', async t => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'nexus-setup-test-'));
  t.after(() => fs.rmSync(dir, { recursive: true, force: true }));
  const filename = path.join(dir, 'config.json');
  const saved = await saveConfig(filename, validate(input()));
  assert.match(saved.DASHBOARD_PASS_HASH, /^scrypt:/);
  assert.ok(!fs.readFileSync(filename, 'utf8').includes(input().password));
  assert.deepEqual(loadConfig(filename), saved);
  await assert.rejects(saveConfig(filename, validate(input())));
  assert.deepEqual(loadConfig(filename), saved);
  if (process.platform !== 'win32') assert.equal(fs.statSync(filename).mode & 0o777, 0o600);
});
test('HTTP setup protects secrets, checks connections, persists and closes', async t => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'nexus-http-test-'));
  const filename = path.join(dir, 'config.json');
  let checks = 0;
  let allow = false;
  let finish;
  const finished = new Promise(resolve => { finish = resolve; });
  const server = await startSetup({ filename, host: '127.0.0.1', port: 0, token: 'test-token', check: async () => { checks++; if (!allow) throw new Error('Testverbindung fehlgeschlagen'); }, onComplete: finish });
  t.after(() => { server.closeAllConnections(); server.close(); fs.rmSync(dir, { recursive: true, force: true }); });
  const url = `http://127.0.0.1:${server.address().port}`;
  const page = await fetch(url);
  assert.equal(page.status, 200);
  assert.ok(!(await page.text()).includes('test-token'));
  assert.match(page.headers.get('content-security-policy'), /frame-ancestors 'none'/);
  const post = (token, body = input()) => fetch(url + '/api/setup', { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-Setup-Token': token, Connection: 'close' }, body: JSON.stringify(body) });
  for (let i = 0; i < 20; i++) assert.equal((await post('wrong')).status, 403);
  assert.equal((await post('wrong')).status, 429);
  assert.equal(checks, 0);
  assert.equal((await post('test-token')).status, 400);
  assert.equal(fs.existsSync(filename), false);
  allow = true;
  const response = await post('test-token');
  assert.equal(response.status, 200);
  assert.deepEqual(await response.json(), { success: true });
  const saved = await finished;
  assert.equal(saved.CLAN_ID, 'ODIN');
  await assert.rejects(startSetup({ filename, onComplete: () => {} }));
});
